--- !ruby/object:Chess
player1: r
player2: "y"
player_turn: 0
board: !ruby/object:Board
  game_state:
  - - !ruby/object:Rook
      color: w
      times_moved: 0
      moves:
      - - 0
        - 1
      - - 0
        - 2
      - - 0
        - 3
      - - 0
        - 4
      - - 0
        - 5
      - - 0
        - 6
      - - 0
        - 7
      - - 0
        - -1
      - - 0
        - -2
      - - 0
        - -3
      - - 0
        - -4
      - - 0
        - -5
      - - 0
        - -6
      - - 0
        - -7
      - - 1
        - 0
      - - 2
        - 0
      - - 3
        - 0
      - - 4
        - 0
      - - 5
        - 0
      - - 6
        - 0
      - - 7
        - 0
      - - -1
        - 0
      - - -2
        - 0
      - - -3
        - 0
      - - -4
        - 0
      - - -5
        - 0
      - - -6
        - 0
      - - -7
        - 0
    - !ruby/object:Knight
      color: w
      times_moved: 0
      moves:
      - - 1
        - 2
      - - 2
        - 1
      - - 2
        - -1
      - - 1
        - -2
      - - -1
        - 2
      - - -2
        - 1
      - - -2
        - -1
      - - -1
        - -2
    - !ruby/object:Bishop
      color: w
      times_moved: 0
      moves:
      - - 1
        - 1
      - - 2
        - 2
      - - 3
        - 3
      - - 4
        - 4
      - - 5
        - 5
      - - 6
        - 6
      - - 7
        - 7
      - - -1
        - 1
      - - -2
        - 2
      - - -3
        - 3
      - - -4
        - 4
      - - -5
        - 5
      - - -6
        - 6
      - - -7
        - 7
      - - 1
        - -1
      - - 2
        - -2
      - - 3
        - -3
      - - 4
        - -4
      - - 5
        - -5
      - - 6
        - -6
      - - 7
        - -7
      - - -1
        - -1
      - - -2
        - -2
      - - -3
        - -3
      - - -4
        - -4
      - - -5
        - -5
      - - -6
        - -6
      - - -7
        - -7
    - !ruby/object:King
      color: w
      times_moved: 0
      moves:
      - - 0
        - 1
      - - 0
        - -1
      - - 1
        - 0
      - - -1
        - 0
      - - 1
        - 1
      - - 1
        - -1
      - - -1
        - 1
      - - -1
        - -1
    - !ruby/object:Queen
      color: w
      times_moved: 0
      moves:
      - - 0
        - 1
      - - 0
        - 2
      - - 0
        - 3
      - - 0
        - 4
      - - 0
        - 5
      - - 0
        - 6
      - - 0
        - 7
      - - 0
        - -1
      - - 0
        - -2
      - - 0
        - -3
      - - 0
        - -4
      - - 0
        - -5
      - - 0
        - -6
      - - 0
        - -7
      - - 1
        - 0
      - - 2
        - 0
      - - 3
        - 0
      - - 4
        - 0
      - - 5
        - 0
      - - 6
        - 0
      - - 7
        - 0
      - - -1
        - 0
      - - -2
        - 0
      - - -3
        - 0
      - - -4
        - 0
      - - -5
        - 0
      - - -6
        - 0
      - - -7
        - 0
      - - 1
        - 1
      - - 2
        - 2
      - - 3
        - 3
      - - 4
        - 4
      - - 5
        - 5
      - - 6
        - 6
      - - 7
        - 7
      - - 1
        - -1
      - - 2
        - -2
      - - 3
        - -3
      - - 4
        - -4
      - - 5
        - -5
      - - 6
        - -6
      - - 7
        - -7
      - - -1
        - 1
      - - -2
        - 2
      - - -3
        - 3
      - - -4
        - 4
      - - -5
        - 5
      - - -6
        - 6
      - - -7
        - 7
      - - -1
        - -1
      - - -2
        - -2
      - - -3
        - -3
      - - -4
        - -4
      - - -5
        - -5
      - - -6
        - -6
      - - -7
        - -7
    - !ruby/object:Bishop
      color: w
      times_moved: 0
      moves:
      - - 1
        - 1
      - - 2
        - 2
      - - 3
        - 3
      - - 4
        - 4
      - - 5
        - 5
      - - 6
        - 6
      - - 7
        - 7
      - - -1
        - 1
      - - -2
        - 2
      - - -3
        - 3
      - - -4
        - 4
      - - -5
        - 5
      - - -6
        - 6
      - - -7
        - 7
      - - 1
        - -1
      - - 2
        - -2
      - - 3
        - -3
      - - 4
        - -4
      - - 5
        - -5
      - - 6
        - -6
      - - 7
        - -7
      - - -1
        - -1
      - - -2
        - -2
      - - -3
        - -3
      - - -4
        - -4
      - - -5
        - -5
      - - -6
        - -6
      - - -7
        - -7
    - !ruby/object:Knight
      color: w
      times_moved: 0
      moves:
      - - 1
        - 2
      - - 2
        - 1
      - - 2
        - -1
      - - 1
        - -2
      - - -1
        - 2
      - - -2
        - 1
      - - -2
        - -1
      - - -1
        - -2
    - !ruby/object:Rook
      color: w
      times_moved: 0
      moves:
      - - 0
        - 1
      - - 0
        - 2
      - - 0
        - 3
      - - 0
        - 4
      - - 0
        - 5
      - - 0
        - 6
      - - 0
        - 7
      - - 0
        - -1
      - - 0
        - -2
      - - 0
        - -3
      - - 0
        - -4
      - - 0
        - -5
      - - 0
        - -6
      - - 0
        - -7
      - - 1
        - 0
      - - 2
        - 0
      - - 3
        - 0
      - - 4
        - 0
      - - 5
        - 0
      - - 6
        - 0
      - - 7
        - 0
      - - -1
        - 0
      - - -2
        - 0
      - - -3
        - 0
      - - -4
        - 0
      - - -5
        - 0
      - - -6
        - 0
      - - -7
        - 0
  - - !ruby/object:Pawn
      color: w
      times_moved: 0
      moves:
      - - 1
        - 0
      - - 2
        - 0
    - !ruby/object:Pawn
      color: w
      times_moved: 0
      moves:
      - - 1
        - 0
      - - 2
        - 0
    - !ruby/object:Pawn
      color: w
      times_moved: 0
      moves:
      - - 1
        - 0
      - - 2
        - 0
    - !ruby/object:Pawn
      color: w
      times_moved: 0
      moves:
      - - 1
        - 0
      - - 2
        - 0
    - !ruby/object:Pawn
      color: w
      times_moved: 0
      moves:
      - - 1
        - 0
      - - 2
        - 0
    - !ruby/object:Pawn
      color: w
      times_moved: 0
      moves:
      - - 1
        - 0
      - - 2
        - 0
    - !ruby/object:Pawn
      color: w
      times_moved: 0
      moves:
      - - 1
        - 0
      - - 2
        - 0
    - !ruby/object:Pawn
      color: w
      times_moved: 0
      moves:
      - - 1
        - 0
      - - 2
        - 0
  - - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
  - - !ruby/object:Pawn
      color: b
      times_moved: 0
      moves:
      - - -1
        - 0
      - - -2
        - 0
    - !ruby/object:Pawn
      color: b
      times_moved: 0
      moves:
      - - -1
        - 0
      - - -2
        - 0
    - !ruby/object:Pawn
      color: b
      times_moved: 0
      moves:
      - - -1
        - 0
      - - -2
        - 0
    - !ruby/object:Pawn
      color: b
      times_moved: 0
      moves:
      - - -1
        - 0
      - - -2
        - 0
    - !ruby/object:Pawn
      color: b
      times_moved: 0
      moves:
      - - -1
        - 0
      - - -2
        - 0
    - !ruby/object:Pawn
      color: b
      times_moved: 0
      moves:
      - - -1
        - 0
      - - -2
        - 0
    - !ruby/object:Pawn
      color: b
      times_moved: 0
      moves:
      - - -1
        - 0
      - - -2
        - 0
    - !ruby/object:Pawn
      color: b
      times_moved: 0
      moves:
      - - -1
        - 0
      - - -2
        - 0
  - - !ruby/object:Rook
      color: b
      times_moved: 0
      moves:
      - - 0
        - 1
      - - 0
        - 2
      - - 0
        - 3
      - - 0
        - 4
      - - 0
        - 5
      - - 0
        - 6
      - - 0
        - 7
      - - 0
        - -1
      - - 0
        - -2
      - - 0
        - -3
      - - 0
        - -4
      - - 0
        - -5
      - - 0
        - -6
      - - 0
        - -7
      - - 1
        - 0
      - - 2
        - 0
      - - 3
        - 0
      - - 4
        - 0
      - - 5
        - 0
      - - 6
        - 0
      - - 7
        - 0
      - - -1
        - 0
      - - -2
        - 0
      - - -3
        - 0
      - - -4
        - 0
      - - -5
        - 0
      - - -6
        - 0
      - - -7
        - 0
    - !ruby/object:Knight
      color: b
      times_moved: 0
      moves:
      - - 1
        - 2
      - - 2
        - 1
      - - 2
        - -1
      - - 1
        - -2
      - - -1
        - 2
      - - -2
        - 1
      - - -2
        - -1
      - - -1
        - -2
    - !ruby/object:Bishop
      color: b
      times_moved: 0
      moves:
      - - 1
        - 1
      - - 2
        - 2
      - - 3
        - 3
      - - 4
        - 4
      - - 5
        - 5
      - - 6
        - 6
      - - 7
        - 7
      - - -1
        - 1
      - - -2
        - 2
      - - -3
        - 3
      - - -4
        - 4
      - - -5
        - 5
      - - -6
        - 6
      - - -7
        - 7
      - - 1
        - -1
      - - 2
        - -2
      - - 3
        - -3
      - - 4
        - -4
      - - 5
        - -5
      - - 6
        - -6
      - - 7
        - -7
      - - -1
        - -1
      - - -2
        - -2
      - - -3
        - -3
      - - -4
        - -4
      - - -5
        - -5
      - - -6
        - -6
      - - -7
        - -7
    - !ruby/object:King
      color: b
      times_moved: 0
      moves:
      - - 0
        - 1
      - - 0
        - -1
      - - 1
        - 0
      - - -1
        - 0
      - - 1
        - 1
      - - 1
        - -1
      - - -1
        - 1
      - - -1
        - -1
    - !ruby/object:Queen
      color: b
      times_moved: 0
      moves:
      - - 0
        - 1
      - - 0
        - 2
      - - 0
        - 3
      - - 0
        - 4
      - - 0
        - 5
      - - 0
        - 6
      - - 0
        - 7
      - - 0
        - -1
      - - 0
        - -2
      - - 0
        - -3
      - - 0
        - -4
      - - 0
        - -5
      - - 0
        - -6
      - - 0
        - -7
      - - 1
        - 0
      - - 2
        - 0
      - - 3
        - 0
      - - 4
        - 0
      - - 5
        - 0
      - - 6
        - 0
      - - 7
        - 0
      - - -1
        - 0
      - - -2
        - 0
      - - -3
        - 0
      - - -4
        - 0
      - - -5
        - 0
      - - -6
        - 0
      - - -7
        - 0
      - - 1
        - 1
      - - 2
        - 2
      - - 3
        - 3
      - - 4
        - 4
      - - 5
        - 5
      - - 6
        - 6
      - - 7
        - 7
      - - 1
        - -1
      - - 2
        - -2
      - - 3
        - -3
      - - 4
        - -4
      - - 5
        - -5
      - - 6
        - -6
      - - 7
        - -7
      - - -1
        - 1
      - - -2
        - 2
      - - -3
        - 3
      - - -4
        - 4
      - - -5
        - 5
      - - -6
        - 6
      - - -7
        - 7
      - - -1
        - -1
      - - -2
        - -2
      - - -3
        - -3
      - - -4
        - -4
      - - -5
        - -5
      - - -6
        - -6
      - - -7
        - -7
    - !ruby/object:Bishop
      color: b
      times_moved: 0
      moves:
      - - 1
        - 1
      - - 2
        - 2
      - - 3
        - 3
      - - 4
        - 4
      - - 5
        - 5
      - - 6
        - 6
      - - 7
        - 7
      - - -1
        - 1
      - - -2
        - 2
      - - -3
        - 3
      - - -4
        - 4
      - - -5
        - 5
      - - -6
        - 6
      - - -7
        - 7
      - - 1
        - -1
      - - 2
        - -2
      - - 3
        - -3
      - - 4
        - -4
      - - 5
        - -5
      - - 6
        - -6
      - - 7
        - -7
      - - -1
        - -1
      - - -2
        - -2
      - - -3
        - -3
      - - -4
        - -4
      - - -5
        - -5
      - - -6
        - -6
      - - -7
        - -7
    - !ruby/object:Knight
      color: b
      times_moved: 0
      moves:
      - - 1
        - 2
      - - 2
        - 1
      - - 2
        - -1
      - - 1
        - -2
      - - -1
        - 2
      - - -2
        - 1
      - - -2
        - -1
      - - -1
        - -2
    - !ruby/object:Rook
      color: b
      times_moved: 0
      moves:
      - - 0
        - 1
      - - 0
        - 2
      - - 0
        - 3
      - - 0
        - 4
      - - 0
        - 5
      - - 0
        - 6
      - - 0
        - 7
      - - 0
        - -1
      - - 0
        - -2
      - - 0
        - -3
      - - 0
        - -4
      - - 0
        - -5
      - - 0
        - -6
      - - 0
        - -7
      - - 1
        - 0
      - - 2
        - 0
      - - 3
        - 0
      - - 4
        - 0
      - - 5
        - 0
      - - 6
        - 0
      - - 7
        - 0
      - - -1
        - 0
      - - -2
        - 0
      - - -3
        - 0
      - - -4
        - 0
      - - -5
        - 0
      - - -6
        - 0
      - - -7
        - 0
